### ISSUE TITLE
Installing via pip does not make the package available

### ISSUE THREAD

**Issue by anderstogern** [ggouzi/markov-word-generator#2]
I want to use this package as a PIP install in a Docker container, but am unable to get it to work.

I have tried simply installing the package in my local environment using `python3 -m pip install markov-word-generator`, which seems to go fine.

Trying to use the package, however, does not work:

`from markov_word_generator import MarkovWordGenerator, WordType`

results in `ModuleNotFoundError: No module named 'markov_word_generator'`

I could include the project by adding it to my code base, but I would very much like to avoid that and simply install it using pip and a requirements file.

**Comment by ggouzi** [comment]
Thanks for the report, the package was malformed.
Published a new revision

```shell
pip3 install markov-word-generator==0.6
cd /tmp
python3    
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from markov_word_generator import MarkovWordGenerator, WordType
>>> generator = MarkovWordGenerator(
...     markov_length=4,
...     dictionary_filename="/tmp/EN-words.dic"
... )
>>> print(generator.generate_word())
diapas
>>> print(generator.generate_word())
punition
>>> print(generator.generate_word())
constoned
```

**Comment by anderstogern** [comment]
That works! Thank you very much!
